import { Blog } from "./blog";

export const newStudioNewViewBlog = new Blog(
    "NEW STUDIO. NEW VIEW.", // -
    "How the need for inspiration fueled the building of a studio.",
    (b: Blog) => {
        b.addParagraph("By Bethlyn Krakauer");
        b.addSpace();
        b.addSubhead("It’s always been a blurry line between my business and personal life.");
        b.addParagraph("I get the concept of separating the two worlds but, for me, achieving work-family balance falls into the category of myth. Friends have become clients. Clients have become friends. Even my husband was a client at one point. A line was probably crossed when my firstborn was given a job number and description “babe-i.e.” in preparation for his arrival. Employees have become family and my kids have been put to work. I have had the same burning desire and vision for years—a space where I get to work any time of day or night, and a creative environment where others can collaborate with me, yet not have to grab lunch in my kitchen. A custom build was inevitable and two years of construction challenges did not break my “Field of Dreams” intent—build it and they will come.");
        b.addSubhead("The innate need for inspiration.");
        b.addParagraph("When I started i.e. design from my Manhattan apartment in my 20s, I was overly focused on my autonomy, yet I was self-aware that I needed to be around people. I knew myself enough to know that my cats did not qualify as a support system, although one did fetch my faxes.");
        b.addParagraph("I recognized early on that my happiness and energy multiplied when I was surrounded by and bouncing ideas off of other creative people. I especially thrived in an environment that inspired me in some way. Whether I could draw from the mini toy collection on my desk, an impromptu collage of discarded Pantone swatches, or a brand new box of Crayolas, the combination of supportive people and inspiring environment always brought out my best ideas.");
        b.addParagraph("My natural love for connecting with people combined with a determined focus, allowed my business to thrive and grow until I assembled my dream team—Nicole, the multi-talented right hand; Lee, the devoted senior designer; Michele, the solid freelancer; Julie Kim, the delightful intern; and David, an intuitive bookkeeper who has since become an accomplished actor.");
        b.addParagraph("There were nights when I fell asleep on my “thinking couch” to the sound of the Epson 3000 slowly printing out the comps to be presented the next morning. West 25th Street was an emerging hot spot for creative firms. The rent was low but the area became desolate after hours. So, even after taking 90 hours of self-defense training, I knew it was best to emerge after sunrise, cab up to East 93rd Street, shower, and do a return trip to make my meeting.");
        b.addParagraph("In those half-conscious moments, I envisioned a big loft space with two entrances—one for my home and the other for business. I fantasized about eliminating my commute and freely working at 1 a.m. if that was when a great idea struck. I imagined Nicole and Lee opening up the studio at 9 a.m. so all progressed smoothly until I stepped over the threshold from home. I found potential space in a converted industrial building down the street, over what would become a Whole Foods, but that was financially unattainable at the time.");
        b.addParagraph("Nonetheless, my humble studio thrived and the area built up nicely. I had access to unlimited late night dinner options and networking came easy with wonderful people and companies in the same building. I had access to the best talent and opportunities in the world. But after boyfriend became husband, and babe-i.e became the priority, things changed.");
        b.addParagraph("Being my own boss allowed me to have flexibility. It was awesome kerning type with one hand and feeding my kid with the other, but the pressure rose and even the most incredible nanny, Beatrice, didn’t stop the gnawing feeling of being torn between work and family. Even with my amazing team beside me, I longed for home to be closer to the office. The market was insane (2000, right before 9/11) so, reluctantly, we started searching outside the City. Renovating was too overwhelming for our two-business-one-baby family. Building was out of the question for the same reason.");
        b.addParagraph("We landed in a place we’d never heard of—Tewksbury, N.J. The wide open areas and tree-lined country roads brought me back to a place I grew up on Long Island. It was the nature, peace and quiet, grass, cows, and breathing space I hadn’t allowed myself to admit I needed. A pretty, yellow, spec house became “i.e. west.” For two years I commuted to the City three days a week. An empty bedroom quickly filled with a second son; Nicole married and relocated to Connecticut; Lee moved to Nashville. Working remotely hadn’t evolved to what it is today so it took until i.e. design’s 13-year anniversary to give up my coveted 212 phone number and embrace letting the City studio go. For the next decade, there were attempts to replicate the magic that was found in that studio. I hired local talent but the flow wasn’t the same and I disliked having people coming through my personal space. My kids’ needs were great. My sleep was not.");
        b.addSubhead("A moment of clarity.");
        b.addParagraph("I accepted that one can have it all—just not at the same time. I turned my focus over to my three kids and projects converted to rebranding their school and leading 125 small to mid-sized children through gala art projects. A mom network provided opportunities for new friendships and, without conscious intention, new business. Getting to know people in the community led to branding a financial advisor, a personal trainer, two attorneys, an upscale clothing boutique, a make-up start-up, and three religious organizations. But, I had come full circle and was back to designing mostly solo.");
        b.addParagraph("Shortly after my husband, Scott, sold his business, my childhood friend and financial advisor, Rob, asked where we saw life going in the next 10 years. Scott quickly replied that he didn’t see anything changing until our then 8-year-old daughter was off to college. Then, something snapped. I started seeing tiny floating stars and Rob’s face went missing. I must have suddenly turned white because I recall him stopping mid-sentence to ask if I was OK. I said yes, but I was not. An overwhelming feeling that something was wrong came and went but I couldn’t place it. A week later, we were tossing out an old mattress. As it lay on the driveway waiting to be dragged away, I plopped down on it for kicks and patted it to signal Scott to take a moment with me. As we watched one of the kids run around, it just hit me. Unplanned, I looked at him and blurted out, “I don’t see myself here for another 10 years. It’s a nice house but I’m not connected to it. I need to design with good people but I can’t have them here. I want to build a house with a separate studio.” And just like that, he said, “OK. Cool.” The very next morning I started to search for what I was looking for.");
        b.addSubhead("The view—and other things that never get old.");
        b.addParagraph("I’ve come to genuinely appreciate how life provides such different perspectives over time and changes what you see as truth. I believed that the main purpose for building this space was to collaborate with a physical team. Ironically, with that option removed from the equation, life connected me with one of my strongest interns when his Boston co-op got cancelled, and the senior designer I longed to work with again, who was now in Nashville. I am discussing a new opportunity with a client who just left New York for Hawaii and connected with a team of web developers from Iowa. I am blown away by the wonderful, unexpected path life has taken and remind myself that this space is simply a place to generate from—as it is with all places.");
        b.addParagraph("I love that feeling of starting something new. If I could work from anywhere, it would be here.");
        b.addParagraph("Bethlyn Krakauer is i.e. design’s Founder and Creative Director.");

        b.addSpace();
        b.addImage("scaffold-view.jpg");
        b.addImageSpace();
        b.addImagePair("tiles.jpg", "scaffold-window.jpg");
    }
);
