import { addBlog, BlogContext } from "./blog";

export const addReconnectingBlog = addBlog("02-reconnecting", (b: BlogContext) => {
    b.addImage("lee.jpg");
    b.addSpace();
    b.addParagraph("By Lee Lipscomb");
    b.addParagraph("Sometimes you don’t know what pulls you to reconnect with someone. Maybe it’s a need to touch the past by speaking to a person from a period of time that you miss a great deal. Or, to just speak to someone that got you. I was struck by this urge on a Saturday morning last August. I had just left a promising job as a creative director. The pandemic lockdown, which had happened just a week into my job, made forming a solid connection with my teammates very difficult. Over a few months, it became regrettably clear that it just wasn’t a good fit and I had to move on. As I had many times before, I thought back to a time and place in my design career where I felt connected, seen, and truly creative. It was easy to pull up: The late ‘90s, a design studio on West 25th street in New York City called i.e. design and its talented owner, Beth Krakauer.");
    b.addParagraph("Like most fortunate events that have happened in my life, a unique series of dots led me to Beth’s office door. My landlord in Brooklyn was a client of hers and casually asked me one day if I knew any senior designers that I would recommend to his friend. I was met at the office by Nicole, a young designer, who surprisingly, knew many of my Hoboken friends. My interview with Beth was one of the fastest I had ever had. She carefully looked over half of my portfolio, abruptly closed it and said, “I’ve seen enough.” My heart dropped and I resigned myself to losing this opportunity and began pulling my portfolio back. But, quick as a flash, she then said, “I know it when I see it. Let’s take a shot and see how it goes.” That was the start of working with i.e. design and the beginning of a wonderfully enduring relationship.");
    b.addParagraph("From my first day on the job, I knew this was going to be a special and unique experience. At 32 years old, I had already worked for several big New York agencies where I felt lost in a sea of account managers pushing tight deadlines. So it was refreshing to work with someone who not only was a great designer, but a keen business person who wanted her team to focus on what we did the best. For me, I just wanted to design and Beth wanted to make things happen, which fit perfectly.");
    b.addParagraph("On paper, it wouldn’t seem that a RISD graduate from New York, Beth, and an Auburn graduate from Alabama, me, would share similar design aesthetics or finish each other’s sentences, but we did. Our collaboration made the work better and I grew as a designer with her encouragement, trust and a delightful work environment that allowed me to be ME. I brought in my mixed CDs to inspire everyone, Nicole’s peaceful and sweet nature calmed us and Beth revved our engines with her infamous chocolate creations and unstoppable spirit. The business brought friends and friends brought business during my time at i.e. design. It was bittersweet when I decided to leave New York in the early 2000s to be closer to my family in the South and to explore my horizons.");
    b.addParagraph("From my new home in Nashville, I expanded my skills and experience in a wide range of avenues. Art directing and producing location photo shoots from Los Angeles to Miami; designing a national magazine; providing voice-overs for commercials and even a cartoon hamster; being an adjunct instructor in university design programs; managing teams as a creative director, and even running my own business. This was the well-worn path for most creatives but I felt the growing layers of management kept me from my love of being a designer. I was shaking my creative self awake by picking up my paint brushes after a decade and exploring nature with my camera. Thoughts of the creative work I had done with Beth, walking up Sixth Avenue with a cup of coffee and toasted sesame bagel from the corner deli were all swirling in my mind when I pressed her contact button.");
    b.addParagraph("The minute the phone rang, I snapped out of these memories and realized I wasn’t sure exactly why I was calling. Standing in my kitchen in Nashville, I felt a moment of panic and then Beth’s friendly voice broke the silence. As mutual fans of examining coincidences as potential opportunities, we realized that we were at similar creative crossroads and that this call was right on time. She wanted to relaunch i.e. design and I wanted to work with her again. The pandemic made the fact that we were separated by 1,500 miles irrelevant. At the end of our call, Beth echoed the past when she said, “Let’s take a shot and see how it goes.”");
    b.addSpace();
    b.addParagraph("Some of Lee’s design work with i.e. design from the early 2000s. Copper, the wonder dog, taking in the Nashville sunrise, 2021.");
    b.addImageSpace();
    b.addImagePair("hudson-river-studios.jpg", "px.jpg");
    b.addImageSpace();
    b.addImagePair("kwe.jpg", "copper.jpg");
    b.addSpace();
    b.addParagraph("Lee Lipscomb is i.e. design’s Senior Designer. Her dog, Copper, has a nicer bed than she does");
});
